name: Robot Framework CI

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  robot-test:
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install robotframework
        pip install robotframework-seleniumlibrary

    - name: Install Chrome
      run: |
        brew install --cask google-chrome

    - name: Install ChromeDriver
      run: |
        brew install chromedriver

    - name: Run Robot Tests
      run: |
        robot --outputdir results tests/

    - name: Upload Robot Report
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: robot-report
        path: results/
        retention-days: 1